### ISSUE TITLE
ListenHandler.OnAsyncAccept throw a exception

### ISSUE THREAD

**Issue by agebullhu** [beetlex-io/BeetleX#71]
line 245 : if (!Socket.AcceptAsync(acceptEventArgs))
调用Server. Dispose() 后 Socket 对象已析构，此代码可能因为异步的原因在继续运行，所以会报异常，直到计数器达到最大数量后退出。
虽然不影响使用，但总感觉这是需要处理的，您可以检查Server的状态来达到目的，或您认为更优雅的方式。
谢谢！

**Comment by beetlex-io** [comment]
更新到v1.6.5.40
