### ISSUE TITLE
数值可能存在溢出风险

### ISSUE THREAD

**Issue by HanJunJun** [beetlex-io/BeetleX#72]
**这段代码是否会存在溢出风险？
long的最大值是922万T，这个是累加当前tcpserver所有会话发来的数据总和。**

![image](https://user-images.githubusercontent.com/16394348/106224211-e033d900-621d-11eb-8289-eaa0d6aba072.png)

**Comment by beetlex-io** [comment]
有这样的风险，只要服务一直运行不停其实用更大的单位都有溢出的可能性。
