### ISSUE TITLE
语雀上的收费资料跟微信上的有啥区别嘛

### ISSUE THREAD

**Issue by HanJunJun** [beetlex-io/BeetleX#73]

**Comment by HanJunJun** [comment]
![image](https://user-images.githubusercontent.com/16394348/106255757-661f4680-6255-11eb-919b-74ffbdd5bbaa.png)
这些属性的注释哪里能看到？

**Comment by beetlex-io** [comment]
如果文章有写就有，我的本地库都没一行注释，文章也只是强行补上去。。。

**Comment by beetlex-io** [comment]
![image](https://user-images.githubusercontent.com/2564178/106258713-2a867b80-6259-11eb-8741-dcef89fc0141.png)
其实很多人私问这问题，看完这图你就能明白。。。这已经超过20的年习惯问题。

**Comment by HanJunJun** [comment]
。。。。
你这个写完还记得啥意思不。。你的代码我付费看文档都看的好吃力，好些个属性要靠看上下文代码关联 猜的。。。
