### ISSUE TITLE
Need a simple http server code example

### ISSUE THREAD

**Issue by zydjohnHotmail** [beetlex-io/BeetleX#74]
Hello:
I need a simple http server, which can accept localhost http post data.
I find the following code for websocket server:
            HttpApiServer server = new HttpApiServer();
            server.Options.SetDebug();
            server.Options.Port = 8000;
            server.Options.LogToConsole = true;
            server.WebSocketReceive = (r, e) =>
            {
                DataBuffer<byte> data = (DataBuffer<byte>)e.Frame.Body;
                string message = Encoding.UTF8.GetString(data.Data, data.Offset, data.Length);
                Console.WriteLine(message);
            };
            server.Open();
            System.Threading.Thread.Sleep(-1);

But I can’t find the corresponding HttpServer code.
By the way, I am using Visual Studio 16.9.0 on Windows 10.
Please advise.

**Comment by beetlex-io** [comment]
https://github.com/beetlex-io/BeetleX-Samples/blob/master/Websocket.CustomFrameDeserialize/Websocket.CustomFrameDeserialize/Program.cs

**Comment by zydjohnHotmail** [comment]
Thanks
