### ISSUE TITLE
BeetleX.Buffers.PipeStream Write 获取buffer偶尔为null

### ISSUE THREAD

**Issue by yuxi214** [beetlex-io/BeetleX#75]
public override void Write(byte[] buffer, int offset, int count)
        {
            WriteAdvance(count);
            while (count > 0)
            {
                IBuffer wbuffer = GetWriteBuffer();
                int len = wbuffer.Write(buffer, offset, count);
                offset += len;
                count -= len;
            }
        }

wbuffer 偶尔为null，是什么情况

**Comment by beetlex-io** [comment]
出现这情况表示连接意外关闭了，相关buffer已经回收所以为空

**Comment by yuxi214** [comment]
不是，好像是跨线程问题，连接没有断开

**Comment by yuxi214** [comment]
能这么快回复太意外了，谢谢

**Comment by yuxi214** [comment]
程序里使用了一个第三方组件，这个第三方组件里一个socket通信，会推消息过来，收到消息使用BeetleX转发。然后出现了这个问题

**Comment by beetlex-io** [comment]
PipeStream并不是线程安全
线程安全发送只能用会话对象的Send方法结合IPacket
http://doc.beetlex.io/?postid=b3c4d8101b8e435c87fc99f1abf8e6a6
