### ISSUE TITLE
Upgrade to Websocket seems to be broken

### ISSUE THREAD

**Issue by fabsmailbox** [beetlex-io/BeetleX#76]
In the latest NuGet Version 2.0.2 the upgrade to websocket mechanism seems to be broken.
When connecting with any websocketclient, the log shows the upgrade to websocket. in the console
But:
mApiServer.GetWebSockets() returns 0. 
mApiServer.TotalConnections() returns 1.

Only when a second websocketclient connects, the GetWebSockets() returns the correct number and SendToWebsocket starts working.
This behaviour was not seen in the previous version.

**Comment by beetlex-io** [comment]
Can you submit the test code?
