### ISSUE TITLE
怎么设置时间呢

### ISSUE THREAD

**Issue by xizhengchao** [beetlex-io/BeetleX#80]
请问，当大量空连接（只连接不发消息），在Accept的阶段时，怎么设置时间呢，不发信息的情况下。  还还有种情况，当发了消息后，后面都不发消息，相当于静默，这个时间呢。这2种情况，确实在这个框架下，需要这两种的安全处理才行。

**Comment by beetlex-io** [comment]
组件提供一个SessionTimeOut配置项，默认多长时间没接收消息会关闭连接，不过要自己调用`server.UpdateSession`.
建议根据自己的规则来制定这种超时场景，组件有connected和receive事件。

**Comment by xizhengchao** [comment]
设置了SessionTimeOut和server.UpdateSession，确实没有效果，就是在connected的时候，当用户没有发消息几秒后，自动断开这个。

**Comment by beetlex-io** [comment]
SessionTimeOut时间单位是秒

**Comment by xizhengchao** [comment]
public override void Connected(IServer server, ConnectedEventArgs e)
        {
            e.Session.TimeOut = 1;
            server.UpdateSession(e.Session);
            base.Connected(server, e);
        }

我在这个地方设置的，设置了没有效果

**Comment by beetlex-io** [comment]
Session.Timeout是组件设置的，你只需要配置服务配置项的SessionTimeOut
