### ISSUE TITLE
server very slow after 5min

### ISSUE THREAD

**Issue by mzelecom** [beetlex-io/BeetleX#84]
hi i used BeetleX in my game server vb.net.but after sometimes server become very slow.when 50 client connected.
this is my code.whats wrong?

`Imports BeetleX
Imports BeetleX.EventArgs
Imports System

Friend Class servers
    Inherits ServerHandlerBase
    Public  server As IServer
	
    Sub server_run()
        server = SocketFactory.CreateTcpServer(Of servers)()
        server.Options.DefaultListen.Port = 8283
        server.Options.SessionTimeOut = 300
        server.Open()
    End Sub

    Public Overrides Sub Connected(ByVal server As IServer, ByVal e As ConnectedEventArgs)
       
        main_form.Connected(server, e)
    End Sub

    Public Overrides Sub Disconnect(ByVal server As IServer, ByVal e As SessionEventArgs)
        main_form.Disconnect(server, e)
    End Sub

    Public Overrides Sub SessionReceive(ByVal server As IServer, ByVal e As SessionReceiveEventArgs)
        Dim pipeStream = e.Stream.ToPipeStream()
        Dim name As String = Nothing
        If pipeStream.TryReadLine(name) Then         
            main_form.SessionReceive(server, e, name)
        End If
    End Sub

End Class`

**Comment by beetlex-io** [comment]
Winform is not thread-safe, Serverhandler accessing winform functionality may produce unintended results
