### ISSUE TITLE
将FastHttpAPI的BeetleX的库调整最新的,图片文件等资源会出错

### ISSUE THREAD

**Issue by Qing1234567** [beetlex-io/BeetleX#89]
大牛你好,首先感谢你的开源库,它真的很灵活和方便,关键是我这种小白也能看明白!
我将BeetleX.FastHttpApi的BeetleX版本调整到git最新版本后发现图片和文件资源出错,.
我将BeetleX的版本调整到nuget的1517版本就是正常的,如果我想要使用最新的BeetleX,我应该怎么解决这个问题呢?

**Comment by beetlex-io** [comment]
BeetleX.FastHttpapi也要升级，新版本的beetlex有些方法可能不兼容旧的BeetleX.FastHttpapi
