### ISSUE TITLE
WriteUTF咨询

### ISSUE THREAD

**Issue by yesyeey** [beetlex-io/BeetleX#92]
大佬您好，咨询个问题  WriteUTF是设置长度和内容的，假如缓存设置的是2048 ， 长度 00 03 内容 为01 02 03   00是在第一个缓存最后一个字节 ,03在第二个缓存的第一个字节,然后色湖之内容，bettlex中解决了这个问题吗？谢谢

**Comment by beetlex-io** [comment]
WriteUTF会根据这情况写入多个buffer,但在ReadUTF就要注意，一般在满足完整协议包的数据长时这个ReadUTF是没问题，网络流接收是不可控所以一般会判断一下Stream.length来处理。如果碰到实际问题最好把代码贴出来

**Comment by yesyeey** [comment]
[BetteleX字节.txt](https://github.com/beetlex-io/BeetleX/files/11354019/BetteleX.txt)
46 30 34 后面的 00 00 就是长度。我想了一个笨方法 判断发送内容字节是奇数还是偶数，如果是奇数,在发送之前补充一位,不知道大佬是否又更好的方法

**Comment by beetlex-io** [comment]
流数据最好不要这样处理，制定一更完善的协议格式
